### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by poing** [poing/laravel-wombatdialer-api#28]
It's time to change `userAuth()` and `passAuth()` to use [session](https://laravel.com/docs/8.x/session) based variables.

```php
session(['wombatUser' => 'alpha']);
session(['WombatPass' => 'alpha']);
$campaign = new Campaign;
$campaign->index();
```

Using `alpha` you should only see two `(2)` campaigns.  *Same goes for the `GUI`.*

----

The methods should be something like this...

```php
function xxxxAuth()
{
  return $request->session()->pull('wombatAuth', $this->userPass);
}
```

---

The **reason** we created `userAuth()` and `passAuth()` is to **allow** the function to be over-ridden in different ways.  

One way is with a customized controller, *although we have no **real** reason to do this.  It's just for flexibility.*

```php
use App\Http\Controllers\Campaign;
class myCampaign extends Campaign
{
  function userAuth()
  {
    return 'customUser';
  }
  function passAuth()
  {
    return 'customPass';
  }
}
```

----
----

We **might** want to consider adding `variables` to the Wombat `construct()` too.

```php
public function __construct($user=null, $pass=null)
    {
        $this->user = $user ?: config('wombatapi.admin.user'); //the config should be changed to session for authentication
        $this->pass = $pass ?: config('wombatapi.admin.pass'); 
    }
```

This *could* allow us to do the following:

```
tinker
>>> $campaign = new Name\Space\Campaign('alpha','alpha');
```

----
----

#### Also...

Let's make the variable name for the `session` a configuration option.  That *could* be set in the config file **-or-** `.env`.  

*This is to add flexibility.*

Up to you, if you put it in the `default` or `wombatdialer` config file.

**Comment by komalraja** [comment]
Now, We extract the `userName`  and `passWord` fields from the  config file.

And we perform authentication (Http::withBasicAuth($this->userAuth() , $this->passAuth())) with the variables from `userAuth()` and `passAuth()`,  which further get its value from `construct()`.
```
  public function __construct()
    {
        $this->user = config('wombatdialer.user');
        $this->pass = config('wombatdialer.pass');
    }
```
To change it to `session based variables`.

```
 $this->user = config('wombatdialer.user'); //could be replaced by session('wombatdialer.user') in the controller?
```

So, each time when we execute API methods, Do we need to pass the `uName` and `pass` to the class `Instance`.?
```
 $campaign = new Name\Space\Campaign('alpha','alpha');
$campaign->show(2);
```

**Comment by poing** [comment]
Authentication will use the `config` *if* no other methods are defined.  

The priority should be:
1. `construct`
1. `session`
1. `config` *the default*

----

As I already described above.  Check if `session` is set **-or-** use the `config`.  Check if `variables` are passed to the `construct` **-or-** use the `config`.

----

`userAuth()` and `passAuth()` are more about providing the user the functionality to use an *alternative* to the others.  *So those methods should **not** be changed.*

**All** the logic, should be in the `construct`.

----

#### Assuming the following:

```php
    /*
    |--------------------------------------------------------------------------
    | Session Variables
    */

   'session' => [
	'user' => env('WOMBAT_SESSION_USER' , 'wbt_user'),
	'pass' =>   env('WOMBAT_SESSION_PASS', 'wbt_pass'),
   ],
```

#### And using these *demo* users:

```
config = 'alpha';
session = 'bravo';
construct = 'charlie';
```

#### We will get the following results:

```php
$test = new Wombat;
$test->userAuth(); // alpha - CORRECTED

Session::put('wbt_user', 'bravo');
$test = new Wombat;
$test->userAuth(); // bravo

$test = new Wombat('alpha', 'alpha');
$test->userAuth(); // alpha

Session::put('wbt_user', 'bravo');
$test = new Wombat('alpha', 'alpha');
$test->userAuth(); // alpha
```

**Comment by poing** [comment]
>So, each time when we execute API methods, Do we need to pass the uName and pass to the class Instance.?
> ```php
> $campaign = new Name\Space\Campaign('alpha','alpha');
> $campaign->show(2);
> ```

It depends on the Laravel Application.  For the `cyanic` project, **yes** we'll **often** pass the credentials in the `construct()`.

**Comment by komalraja** [comment]
In the above example,

```
config = 'alpha';
session = 'bravo';
construct = 'charlie';
```
```
$test = new Wombat;
$test->userAuth(); // alpha  - CORRECTED
```
How will it displays `charlie` from `construct()`?

```
 public function userAuth()
    {
        return 'charlie'; ($this->uName)
    }
```
How will it comes from `construct()`? ,Since `construct(uName=null, Pass =null)` , won't it take the value from the config which is `alpha`? or we are returning by overriding the name in the userAuth() ?

**Comment by poing** [comment]
#### Session

We **don't know** what `key` a user will **want** to use in their Laravel Application.  It could be anything!

So... We add a `config` item, that let's the user change the `key`  But it also sets a default `key` the user **could** use.

```php
'session' => [
  'user' => env('WOMBAT_SESSION_USER' , 'default_key'),
],
```

*Of course*, the *default* `key` name should be something **unique**.  *Like: `wombatdialer_username`, so it's not used by accident in a Laravel Application.*
##### In the Laravel Application

`some_other_key` is the `key` used for the `session`.  The user sets the `value` *somewhere* in the Laravel Application.

```ini
# .env
WOMBAT_SESSION_USER=some_other_key
```

```php
Session::put('some_other_key', 'brian.lavallee');
```

##### Retrieving the value

We can get the value, *because* the `key` was defined **by the user** in the `config` **-or-** `.env` for the Laravel Application.

This let's us to get the `value` from the `session`, *even if we do not know what it is in the Laravel Application.*  

**AND...** 

We don't **force** the user to use `default_key` as the `key`, *using the `default_key` is **optional** in the Laravel Application.*

```php
if (Session::has(config('wombatdialer.session.user'))) {  // Check if some_other_key is set
  return Session::get(config('wombatdialer.session.user'));  // Returns "brian.lavallee"
}
```

**Comment by komalraja** [comment]
> We don't force the user to use default_key as the key, using the default_key is optional in the Laravel Application.

```
if (Session::has(config('wombatdialer.session.user'))) {  // Check if some_other_key is set
  return Session::get(config('wombatdialer.session.user'));  // Returns "brian.lavallee"
}
```
In the above code, If the user uses the `default_key`, and if the `default_key` value is set in the _laravel application_.

```
Session::put('default_key', 'brian.lavallee');// that too returns "brain.lavallee"
```
Is this correct?

**Comment by poing** [comment]
> In the above code, If the user uses the default_key, and if the default_key value is set in the laravel application.
>
> ```
> Session::put('default_key', 'brian.lavallee');// that too returns "brain.lavallee"
> ```
> Is this correct?

The below **sets** *`(put)`* the `session` `variable` with a the `key` of `default_key`
```php
Session::put('default_key', 'brian.lavallee'); // Store session variable
```

**Comment by poing** [comment]
Using the package in a Laravel Application, the user should be able to:

1. Use the default user/pass
1. Customize the user/pass in the `config` or `.env`, *replacing the default user/pass*
1. Set/use the user/pass from `session` `variables`, *using the default `key` names*
1. Customize the user/pass `key` names used for the `session` in the `config` or `.env`
1. Set/use the user/pass when instantiating a `class`, *aka passing `variables` to the `construct()`*

----

All the above are handled by the `construct()`, **something like** this:

```php
function construct($user, $pass)
{
  if ($user)
  {
    $this->user = $user;
  } elseif (Session::has(config('session.key'))) {
    $this->user = Session::get(config('session.key'));
  } elseif {
    $this->user = config('user')
  }
}
```

**Comment by komalraja** [comment]
Okay, _I understood the above 5 statements_.

In the `construct()`, If we have like the below code,

```
 public function __construct($user = null, $pass = null)
    {
        $this->user = $user ?: config('wombatdailer.user');
        $this->pass = $pass ?: config('wombatdialer.pass');
  }
```
In the `UserAuth()` and `passAuth()`. I have tried the below.

```
public function userAuth()
    {
      Session::put('wbt_user', 'Delta');
      if(construct('alpha','alpha')
      {
        return $this->user = $user; //not working 
    }
   elseif (Session::has(config('wombatdailer.session.user')))
    {  
  return Session::get(config('wombatdailer.session.user'));  //works
   }
else {
    return $this->user= config('wombatdailer.user');//Else it works.
    }
    }
```
`construct()` in the `If` statement is not working.  Is this way to include a function inside the `If` statement ?

**Comment by poing** [comment]
You should **not** be touching `userAuth()`, *that was an early idea.*  
It breaks the *desired* priorities, by making `session` the highest priority.

I guess I have to revise the list and update priorities.

1. `userAuth()` & `passAuth()` over-ride
1. construct
1. session
1. config the default


----

Using the package in a Laravel Application, the user should be able to:

1. Use the default user/pass
1. Customize the user/pass in the `config` or `.env`, *replacing the default user/pass*
1. Set/use the user/pass from `session` `variables`, *using the default `key` names*
1. Customize the user/pass `key` names used for the `session` in the `config` or `.env`
1. Set/use the user/pass when instantiating a `class`, *aka passing `variables` to the `construct()`*
1. **Over-ride `userAuth()` and `passAuth()` with their own user/pass methods**, *by `extending` the `class`*

**Comment by komalraja** [comment]
In the `abstract wombat` class we have a `userAuth()` and `passAuth()` .

```
 public function userAuth()
    {

     return $this->user; //which returns the userName from the construct()
    }
    public function passAuth()
    {
     return $this->pass;
    }
```
If we need to **over-ride** the `userAuth() ` and `passAuth()`. Should we need to create a new class which extends the base class `Campaign` like the below.

```
class Test extends Campaign
{
    public function userAuth()
    {
    return 'alpha'; //It over-rides the uName from construct()
    }
    public function passAuth()
    {
     return 'alpha';
    }

}
```
Do you the mean the point no. 6 like the above code?
> 6.  Over-ride userAuth() and passAuth() with their own user/pass methods, by extending the class

**Comment by poing** [comment]
Yes, that is what I mean by over-riding *from* the Laravel Application.
It supersedes all other methods.  *Because we call `userAuth()` and `passAuth()` **last**, from the `Http::method()`.*

**Comment by komalraja** [comment]
As discussed, I have implemented all the methods based on the priority in the `construct()`.

```
 public function __construct($user= null , $pass= null)
    {
        //Session::put('wbt_user', 'KomalRaja');
       if(isset($user) && isset($pass))
        {
         $this->user = $user;
         $this->pass = $pass;
        }
        if(Session::has(config('wombatdialer.session.user'))) {  
           $this->user =  Session::get(config('wombatdialer.session.user'));
          }
         else{
        $this->user =  config('wombatdialer.user');
        $this->pass =  config('wombatdialer.pass');
        }
    }
```
1. `construct()` is passed with `userName` and `password`, It takes the `userName` and `password` from the `construct()`. It works fine.
2. If `construct()` is not passed with parameters, it returns the `userName ` and `password` from the `config` file.
3. If we store the variables in the `Session`, that value is retrieved as `user` and `pass`. If we set the key 
```
          Session::put('wbt_user', 'alpha');
         Session::put('wbt_pass', 'alpha');
          elseif (Session::has(config('wombatdialer.session.user'))) {  
           $this->user =  Session::get(config('wombatdialer.session.user'));
           $this->pass = Session::get(config('wombatdialer.session.pass'));
          }
```
The above works fine!
But, to check whether both `userName` and `passWord` is set.
Can't it be like the below.?
```
   elseif (Session::has(config('wombatdialer.session.user') &&  config('wombatdialer.session.pass'))) {  
//
}

**Comment by poing** [comment]
```
>>> Session::put('a','alpha')
=> null
>>> Session::put('b','bravo')
=> null
>>> Session::has('a')
=> true
>>> Session::has('b')
=> true
>>> Session::has('a') && Session::has('b')
=> true
>>> (Session::has('a') && Session::has('b'))
=> true
>>> (Session::has('a') && Session::has('c'))
=> false
>>> 
```
