### ISSUE TITLE
Configuration Files

### ISSUE THREAD

**Issue by poing** [poing/laravel-wombatdialer-api#5]
Were going to create two `(2)` configuration files.

```
src/config/default.php
src/config/wombatdialer.php
```

**DO NOT** use the `invite-comm.jp` address *anywhere* in the **public** repository.  

----

###### default.php
```php
return [
   'admin' => [
        'user' => env('WOMBAT_USER', 'demoadmin'),
        'pass' => env('WOMBAT_PASS', 'demo'),
    ],
];
```

###### wombatdialer.php

We will **comment out** the `admin` settings.  This `file` will be installed in the Laravel Application.  *Will show you how in later task.*

```php
return [
    /*
    |--------------------------------------------------------------------------
    | Add Comments
    |--------------------------------------------------------------------------
    |
    | Explain these settings
    |
    */

   'url' => [
	'scheme' => env('WOMBAT_SCHEME' , 'http'),
	'host' =>   env('WOMBAT_HOST', 'localhost'),
	'port' =>   env('WOMBAT_PORT' , '8080'),
	'path' =>   env('WOMBAT_PATH', '/wombat/api/'),
   ],

    /*
    |--------------------------------------------------------------------------
    | Add Comments
    |--------------------------------------------------------------------------
    |
    | Explain these settings
    |
    */

    //  'admin' => [
    //    'user' => env('WOMBAT_USER', 'demoadmin'),
    //    'pass' => env('WOMBAT_PASS', 'demo'),
    // ],
];
```

----

We use two `(2)` files, so we can hide some settings.  Allow the user to change default values, uncomment and change others. 

We **will** apply the `admin` settings from the default, *the user has to uncomment the setting to change it.*

**Comment by komalraja** [comment]
Do we need to create 2 `Config` files `Default` and  `wombatdialer` in  the poing/laravel-wombatdialer-api package  , under the src folder?

**Comment by poing** [comment]
> Do we need to create 2 Config files Default and wombatdialer in project_name ?

**No!**  In the package!

> src/config/default.php
> src/config/wombatdialer.php
